const {
  KKT_ADD_LABEL,
  MENU_LABEL,
  CANCEL_LABEL,
  KKT_SHOW_LABEL,
  REGISTRATION_REPORT,
  REREGISTARTION_REPORT,
  SHIFT_OPEN_REPORT,
  SHIFT_CLOSE_REPORT,
  CASHDESK_RECEIPT,
  CASHDESK_RECEIPT_CORRECTION,
} = require('../constants/commands');

const START = [[KKT_ADD_LABEL, KKT_SHOW_LABEL], [MENU_LABEL]];
const CANCEL_KEYBOARD = [[CANCEL_LABEL]];
const KKT_GENERATE_JSON_KEYBOARD = [
  [REGISTRATION_REPORT, REREGISTARTION_REPORT],
  [SHIFT_OPEN_REPORT, SHIFT_CLOSE_REPORT],
  [CASHDESK_RECEIPT, CASHDESK_RECEIPT_CORRECTION],
];

module.exports = {
  START_KEYBOARD: START,
  START,
  CANCEL_KEYBOARD,
  KKT_GENERATE_JSON_KEYBOARD,
};
